### PR TITLE
Release v0.1 6/3/2021

### PR DESCRIPTION
**Pull request by ivanbukhtiyarov**

### CODE REVIEW

**Comment by ivanbukhtiyarov** [comment]
@qpep3b @alexander135 @cyberdile @alexandraartemyeva

**Comment by ivanbukhtiyarov** [comment]
For: https://github.com/ivanbukhtiyarov/elevators/issues/41

**Review by cyberdile — APPROVED** [review]
NICE JOB
image

**Review by alexander135 — CHANGES_REQUESTED** [review]
we need less prints in our code

**Comment by ivanbukhtiyarov** [comment]
> we need less prints in our code

@alexander135 sure, don't know why was approved :(

**Comment by ivanbukhtiyarov** [comment]
> we need less prints in our code 
now less @alexander135

**Review by cyberdile — APPROVED** [review]

**Review by alexander135 — APPROVED** [review]

**Pull request merged**
